title: WAVE
logo: /assets/img/logo.jpg
email: person@address.com
description: WAVE Collaboration Website
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://github.com/vaibhavvikas

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
